=== badeeul/Learning/metadata/json_schemas/feeds/feed_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Platform Services Ingest Feed",
    "description": "A feed that represents which dataset configs to run",
    "type": "object",
    "properties": {
        "feedName": {
            "type": "string"
        },
        "feedDescription": {
            "type": "string"
        },
        "workLoadType": {
            "type": "string"
        },
        "skipProductLoad": {
            "type": "boolean"
        },
        "dataDeduplicationAlert": {
            "type": "boolean"
        },
        "deduplicationAlertTemplate": {
            "type": "string"
        },
        "datasetsConfig": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "datasetType": {
                        "$ref": "enums.json#/definitions/datasetType"
                    },
                    "datasets": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "fileName": {
                                    "type": "string"
                                },
                                "sourceConfigFolderName": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "fileName",
                                "sourceConfigFolderName"
                            ]
                        },
                        "minItems": 1
                    }
                },
                "required": [
                    "datasetType",
                    "datasets"
                ]
            },
            "minItems": 1
        }
    },
    "required": [
        "feedName",
        "feedDescription",
        "workLoadType",
        "skipProductLoad",
        "dataDeduplicationAlert",
        "deduplicationAlertTemplate",
        "datasetsConfig"
    ]
}

=== badeeul/Learning/metadata/feeds/demo_product.json
{
    "feedName": "demo_product",
    "feedDescription": "This is a demo feed for Demo Data Product used as a refernce to setup a feed.",
    "workLoadType": "dp-spark",
    "skipProductLoad": false,
    "dataDeduplicationAlert": false,
    "deduplicationAlertTemplate": "deduplication_msg",
    "datasetsConfig": [
        {
            "datasetType": "database",
            "datasets": [
                {
                    "fileName": "claimant",
                    "sourceConfigFolderName": "demo_sqldb"
                },
                {
                    "fileName": "claims_catcodes",
                    "sourceConfigFolderName": "demo_sqldb"
                }
                

            ]
        },
        {
            "datasetType": "file",
            "datasets": [
                {
                    "fileName": "massive_claims",
                    "sourceConfigFolderName": "demo_file"
                },
                {
                    "fileName": "dop_pdos_webreport",
                    "sourceConfigFolderName": "demo_file"
                },
                {
                    "fileName": "homeowner_policy",
                    "sourceConfigFolderName": "demo_file"
                },
                {
                    "fileName": "homeowner_policy_blob",
                    "sourceConfigFolderName": "demo_file"
                }
            ]
        }
    ]
}

=== badeeul/Learning/metadata/feeds/claims_transaction_sample.json
{
    "feedName": "claims_transaction_sample",
    "feedDescription": "This is a feed for Claims Transaction Data Product (sample data)",
    "workLoadType": "dp-spark",
    "skipProductLoad": true,
    "dataDeduplicationAlert": true,
    "deduplicationAlertTemplate": "deduplication_msg_claims",
    "datasetsConfig": [
        {
            "datasetType": "database",
            "datasets": [
                {
                    "fileName": "transaction_uwcoverage",
                    "sourceConfigFolderName": "iis_transaction_sample"
                }
            ]
        }
    ]
}

=== badeeul/Learning/metadata/feeds/claims_transaction_historical.json
{
    "feedName": "claims_transaction_historical",
    "feedDescription": "This is a feed for Claims - IIS Historical Incremental Data Load",
    "workLoadType": "dp-spark",
    "skipProductLoad": true,
    "dataDeduplicationAlert": true,
    "deduplicationAlertTemplate": "deduplication_msg",
    "datasetsConfig": [
        {
            "datasetType": "database",
            "datasets": [
                {
                    "fileName": "transaction_uwcoverage",
                    "sourceConfigFolderName": "iis_transaction_historical"
                },
                {
                    "fileName": "claimstrans",
                    "sourceConfigFolderName": "iis_transaction_historical"
                }

            ]
        }
    ]
}

=== badeeul/Learning/metadata/feeds/claims_reserves.json
{
    "feedName": "claims_reserves",
    "feedDescription": "This is a feed for Claims Handling CTI Data Product",
    "workLoadType": "dp-spark",
    "skipProductLoad": false,
    "dataDeduplicationAlert": true,
    "deduplicationAlertTemplate": "deduplication_msg_claims",
    "datasetsConfig": [
        {
            "datasetType": "database",
            "datasets": [
                {
                    "fileName": "cl_occurrence",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "claimant",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "claims_catastrophe",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "claims_catcodes",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "claims_causeofloss",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "claims_extra",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "claims_lossdetail",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "insured",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "mgtrans_coverages",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "mgtrans",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "payments",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "reserves",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "uwbuildings",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "wcclaim",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "wclocnam",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "cl_coverage",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "claims_caextra",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "claims_cavehicles",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "claims_dbextra",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "injury",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "pc_coverage_names",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "pc_products",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "transaction_uwcoverage",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "uwvehicles",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "accident",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "injuryclass",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "pc_coverage_reporting",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "lookups",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "bpclass",
                    "sourceConfigFolderName": "iis_data"
                },
                {
                    "fileName": "wcinfo",
                    "sourceConfigFolderName": "iis_data"
                }
            ]
        },
        {
            "datasetType": "file",
            "datasets": [
                {
                    "fileName": "massive_claims",
                    "sourceConfigFolderName": "accounting"
                },
                {
                    "fileName": "bop_resseg",
                    "sourceConfigFolderName": "accounting"
                },
                {
                    "fileName": "ca_resseg",
                    "sourceConfigFolderName": "accounting"
                },
                {
                    "fileName": "ho_resseg",
                    "sourceConfigFolderName": "accounting"
                },
                {
                    "fileName": "wc_resseg",
                    "sourceConfigFolderName": "accounting"
                }
            ]
        }
    ]
}

=== badeeul/Learning/metadata/feeds/demo_extract.json
{
    "feedName": "demo_product",
    "feedDescription": "This is a demo feed for Demo Data Product used as a refernce to setup a feed.",
    "workLoadType": "dp-spark",
    "skipProductLoad": true,
    "dataDeduplicationAlert": false,
    "deduplicationAlertTemplate": "deduplication_msg",
    "datasetsConfig": [
        {
            "datasetType": "file",
            "datasets": [
                {
                    "fileName": "nws",
                    "sourceConfigFolderName": "demo_api"
                }
            ]
        }
    ]
}

=== badeeul/Learning/metadata/feeds/claims_transaction.json
{
    "feedName": "claims_transaction",
    "feedDescription": "This is a feed for Claims Transaction Data Product",
    "workLoadType": "dp-spark",
    "skipProductLoad": false,
    "dataDeduplicationAlert": true,
    "deduplicationAlertTemplate": "deduplication_msg",
    "datasetsConfig": [
        {
            "datasetType": "database",
            "datasets": [   
                { "fileName": "accident", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "address", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "agency", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "aslob_codes", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "catcode", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "cl_coverage", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "cl_occurrence", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claimant", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claimant_status_asof", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_accidentdescriptionnarrative", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_adjustor_stats", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_caextra", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_catastrophe", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_catcodes", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_causedetail", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_causeofloss", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_cavehicles", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_dbextra", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_extra", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claims_lossdetail", "sourceConfigFolderName": "iis_transaction" },
		        { "fileName": "dbo_claimstrans_ct", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "claimstrans_types", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "counties", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "employee", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "injury", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "insured", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "lob", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "lookups", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "payments", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "pc_coverage_ifields", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "pc_coverage_names", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "pc_coverage_reporting", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "provider", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "provtype", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "reserves", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "reservelimits", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "uwbuildings", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "uwvehicles", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "wcclaim", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "wcpmttyp", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "dbo_transaction_uwcoverage_ct", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "dbo_transaction_uwhomes_ct", "sourceConfigFolderName": "iis_transaction" },
                { "fileName": "dbo_wclocnam_ct", "sourceConfigFolderName": "iis_transaction" }
            ]
        }    
    ]
}

=== badeeul/Learning/metadata/feeds/claims_transaction_cdc_test.json
{
    "feedName": "claims_transaction_cdc_test",
    "feedDescription": "This is a test feed for Claims Transaction Data Product (CDC tables)",
    "workLoadType": "dp-spark",
    "skipProductLoad": true,
    "dataDeduplicationAlert": true,
    "deduplicationAlertTemplate": "deduplication_msg_claims",
    "datasetsConfig": [
        {
            "datasetType": "database",
            "datasets": [
                {
                    "fileName": "dbo_transaction_uwcoverage_ct",
                    "sourceConfigFolderName": "iis_transaction"
                }
            ]
        }
    ]
}
